name: 'check-gradle-version'
description: 'GitHub Action for Gradle version verification'
author: 'madhead'
inputs:
  gradlew:
    required: false
    default: 'gradlew'
    description: 'Relative path to gradlew executable'
outputs:
  version:
    description: 'Project Gradle version'
  current:
    description: 'Current Gradle version'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'chevron-up'
  color: 'orange'
